### ISSUE TITLE
Model selection does not work

### ISSUE THREAD

**Issue by justinthelaw** [defenseunicorns/leapfrog-ui#18]
**The issue:** The model selection setting does not properly switch to the selected model when the model is not the "DEFAULT_MODEL" as annotated in the configs.json.

**To replicate:** install and run 1 or more model backends that are not directly related to the "DEFAULT_MODEL" within the configs.json. For example, instead of gpt-4 or mpt-7b, you have ctransformers (synthia-7b) as the only reachable backend via an API (leapfrogai-api). Select the ctransformers model in the system settings. Send a message via the chat feature. This results in a 405 method not allowed.

**Proof:** Hard-code the server's chatCompletion params to have `model="ctransformers"`. Try sending a message via the chat feature again. This will properly pass the request through the API to the appropriate model backend.

**Comment by CollectiveUnicorn** [comment]
Fixed in https://github.com/defenseunicorns/leapfrog-ui/commit/52eb27921ddc455ebd971b1db16ba264a9e5933e
